services:
  app:
    build: .
    container_name: torbware_theater
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./library:/app/library
      - ./tmp:/app/tmp
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY}
    extra_hosts:
      - "host.docker.internal:host-gateway"