version: '3.8'

services:
  server:
    build: ./server
    container_name: theater_server
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./library:/usr/src/app/library
      - ./server/src:/usr/src/app/server/src # Monta código fonte para dev
    environment:
      - PORT=3000
      - PYTHON_WORKER_PATH=/usr/src/app/worker/main.py # Caminho dentro do container
    depends_on:
      - worker

  worker:
    build: ./worker
    container_name: theater_worker
    restart: always
    volumes:
      - ./library:/usr/src/app/library
      - ./tmp:/usr/src/app/tmp
      - ./worker:/usr/src/app/worker # Monta código fonte para dev
    environment:
      - TMDB_API_KEY=${TMDB_API_KEY} # Pega do .env na raiz